### ISSUE TITLE
 Met the problem: AttributeError: 'str' object has no attribute 'shape'

### ISSUE THREAD

**Issue by AlinaXie** [DorBernsohn/multimodal_hateful_memes_classification#2]
Hi,
I am interested in this project. So I try to run this code.
But when I run the "history = cls.train(preprocess.data, vision_model=vision_model)", it occurs some errors, but I have tried some methods, which can not solve this problem.
<img width="662" alt="result3" src="https://user-images.githubusercontent.com/46320082/113105880-acccf500-9234-11eb-9494-84b866231eff.PNG">

<img width="761" alt="result4" src="https://user-images.githubusercontent.com/46320082/113105921-b8202080-9234-11eb-9422-c0f7fd1a7d96.PNG">

I would be appreciated if I can receive your help. Thanks.

**Comment by DorBernsohn** [comment]
On which project? concatBERT/odBERT?

**Comment by DorBernsohn** [comment]
I updated the Requirements in the README. It's now works fine.

**Comment by AlinaXie** [comment]
hi~is concatBERT. Does this mean that the problem will be solved if I follow the README to configure the environment?

**Comment by DorBernsohn** [comment]
Yes, i did this on a clean colab environment and it went smoothly.

**Comment by AlinaXie** [comment]
thanks for your reply!
